---
- name: Install and configure Apache Tomcat
  hosts: webservers
  become: true
  vars:
    pkg_name: tomcat
    tomcat_version: 9.0.46
    tomcat_url: "https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version }}/v{{ tomcat_version }}.tar.gz"

  tasks:
    - name: Download Apache Tomcat archive
      ansible.builtin.get_url:
        url: "{{ tomcat_url }}"
        dest: "/tmp/{{ pkg_name }}.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/{{ pkg_name }}.tar.gz"
        dest: "/opt/"
        remote_src: true

    - name: Rename Tomcat directory
      ansible.builtin.command:
        cmd: "mv /opt/apache-tomcat-{{ tomcat_version }} /opt/{{ pkg_name }}"
        creates: "/opt/{{ pkg_name }}"

    - name: Set environment variables for Tomcat
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/{{ pkg_name }}"
        create: yes

    - name: Reload environment variables
      ansible.builtin.command:
        cmd: "source /etc/environment"

    - name: Start Tomcat service
      ansible.builtin.service:
        name: "{{ pkg_name }}"
        state: started
