- hosts: webservers
- hosts: webservers
  become: true
  tasks:
    - name: install httpd
      package:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
    - name: Deploy index.html on httpd
      copy:
        src: index.html
        dest: /var/www/html
    - name: restart httpd
      service:
        name: httpd
        state: restarted
